# Generated by Django 2.0.2 on 2021-02-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time',
        ),
    ]
